[package]
name = "triforces-demo"
version = "1.1.4"
authors = ["Stallmanifold <stallmanifold@gmail.com>"]
build = "build.rs"

[dependencies]
chrono = "0.4.6"
glfw = "0.25.0"
log = "0.4.6"
stb_image = "0.2.2"
serde = "1.0.80"
serde_derive = "1.0.80"
toml = "0.4.8"
simple_cgmath = { git = "https://github.com/stallmanifold/simple-cgmath" }
wavefront_obj = { git = "https://github.com/stallmanifold/wavefront-obj" }

[build-dependencies]
gl_generator = "0.10.0"

[profile.dev]
debug = true

[features]
build_for_install = []
