[package]
name = "triforces-demo"
version = "0.1.0"
authors = ["Stallmanifold <stallmanifold@gmail.com>"]

[dependencies]
chrono = "0.4.4"
glfw = "0.23.0"
gl = "0.10.0"
scan_fmt = "0.1.3"
stb_image = "0.2.2"
simple_cgmath = { git = "https://github.com/stallmanifold/simple-cgmath" }
