log_file = "triforces-demo.log"

# Asset paths
shader_path = "shaders"
shader_version = "420"
asset_path = "assets"


[platform]
# Platform specific parameters.

[platform.macos]
shader_version = "330"

[platform.windows]
shader_version = "330"

[platform.linux]
shader_version = "420"
